### ISSUE TITLE
请问如何使用

### ISSUE THREAD

**Issue by manyhelp** [cnjm/postcss-px-to-viewport#1]
大佬，这个怎么使用，刚学前端。

项目 vite + vue3 + vant  用的750 设计稿，怎么适配

**Comment by YouLiLiao** [comment]
![image](https://user-images.githubusercontent.com/11286354/202843119-c77db6fd-3ef2-4050-88ea-bcc80a9701a6.png)

没有看文档吗？作者在原来的[postcss-px-to-viewport](https://github.com/evrone/postcss-px-to-viewport)插件基础上做了修改，暴露了一个`customFun()`的方法，返回匹配到的css文件路径，根据路径判断是否是vant文件再决定返回是375还是750。
